saleskg/article/urls.py
from django.urls import path,include
from.views import ArticleListView,ArticleDetailView


urlpatterns = [
    path('list/', ArticleListView.as_view(),name='article_list'),
    path('<int:pk>/', ArticleDetailView.as_view(),name='article_detail'),
]

saleskg/saleskg/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('article/', include('article.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleskg/article/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=64, verbose_name='Название', blank=True, null=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=64, verbose_name='Название', blank=True, null=True)
    text = models.TextField(verbose_name='Описание обьявления', blank=True, null=True)
    owner = models.CharField(verbose_name='Автор', max_length=64, blank=True, null=True)
    price = models.PositiveSmallIntegerField(verbose_name='Цена')
    end_date = models.DateField(verbose_name='Дата окончания')
    category = models.ForeignKey(Category,on_delete=models.CASCADE, verbose_name='Категория', blank=True, null=True)


class ArticleImages(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE, verbose_name='Обюявление', blank=True, null=True)
    image = models.ImageField(verbose_name='Изображение', upload_to='article_image/')

saleskg/article/views.py
from django.shortcuts import render
from .models import Article
from django.views.generic import ListView,DetailView


class ArticleListView(ListView):
    model = Article
    template_name = 'article/article_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles']=Article.objects.all()
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article/article_detail.html'
    context_object_name = 'article'

saleskg/templates/article/article_detail.html
    <h1>{{article.title}}</h1>
    <p>{{article.text}}</p>
    <p>{{article.owner}}</p>
    <p>{{article.price}}</p>
    <p>{{article.end_date}}</p>
    <p>{{article.category}}</p>
    {% for image in article.articleimages_set.all%}
        <img src="{{image.image.url}}">
    {%endfor%}

saleskg/templates/article/article_list.html
{%for item in articles %}
    <h1><a href="{% url 'article_detail' pk=item.pk %}">{{item.title}}</a></h1>
    <p>{{item.text}}</p>
    <p>{{item.owner}}</p>
    <p>{{item.price}}</p>
    <p>{{item.end_date}}</p>
    <p>{{item.category}}</p>
    {% for image in item.articleimages_set.all%}
        <img src="{{image.image.url}}">
    {%endfor%}
{%endfor%}